import { Bot, ChevronDown, ChevronUp, Loader2 } from 'lucide-react'
import { useState } from 'react'

interface ExplanationCardProps {
  explanation: string | null
  isLoading?: boolean
  model?: string         // e.g. "llama-3.1-70b-versatile"
}

export default function ExplanationCard({
  explanation,
  isLoading = false,
  model = 'Groq LLM',
}: ExplanationCardProps) {
  const [expanded, setExpanded] = useState(true)

  return (
    <div className="bg-[#1E293B] border border-slate-700/60 rounded-2xl overflow-hidden shadow-lg">
      {/* Header */}
      <button
        type="button"
        onClick={() => setExpanded((v) => !v)}
        className="w-full flex items-center justify-between px-5 py-4 hover:bg-white/[0.02] transition"
        aria-expanded={expanded}
        aria-controls="explanation-body"
      >
        <div className="flex items-center gap-3">
          <div className="flex items-center justify-center w-8 h-8 rounded-lg bg-violet-500/15 border border-violet-500/25">
            <Bot className="w-4 h-4 text-violet-400" />
          </div>
          <div className="text-left">
            <p className="text-sm font-semibold text-slate-200">AI Explanation</p>
            <p className="text-[11px] text-slate-500">{model}</p>
          </div>
        </div>
        {expanded ? (
          <ChevronUp className="w-4 h-4 text-slate-500" />
        ) : (
          <ChevronDown className="w-4 h-4 text-slate-500" />
        )}
      </button>

      {/* Body */}
      {expanded && (
        <div id="explanation-body" className="px-5 pb-5 pt-1">
          <div className="border-t border-slate-700/50 pt-4">
            {isLoading ? (
              <div className="flex items-center gap-3 text-slate-400 py-4">
                <Loader2 className="w-5 h-5 animate-spin text-violet-400" />
                <span className="text-sm">Generating explanation…</span>
              </div>
            ) : explanation ? (
              <div className="space-y-3">
                {/* Typewriter-style paragraphs */}
                {explanation.split('\n').filter(Boolean).map((para, i) => (
                  <p key={i} className="text-sm text-slate-300 leading-relaxed">
                    {para}
                  </p>
                ))}
              </div>
            ) : (
              <p className="text-slate-500 text-sm italic py-2">
                No explanation available.
              </p>
            )}
          </div>

          {explanation && !isLoading && (
            <div className="mt-4 flex items-center gap-2 pt-3 border-t border-slate-700/40">
              <span className="inline-flex items-center gap-1.5 text-[11px] text-slate-500">
                <span className="inline-block w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse" />
                Generated by {model}
              </span>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
